## valid uuid = 8f4b7b9c-3f7a-4b6c-8b0c-1c9c5b8b9b6a



### Create Category
# @name createCategory
POST http://localhost:3000/categories
Content-Type: application/json

{
    "name": "Category 1",
    "description": "Description 1"
}
###

@categoryId = {{createCategory.response.body.data.id}}

### Search Categories
GET http://localhost:3000/categories

### Find One Category
GET http://localhost:3000/categories/{{categoryId}}



### Create Genre
# @name createGenre
POST http://localhost:3000/genres
Content-Type: application/json

{
    "name": "Genre 1",
    "categoryIds": [
        "{{categoryId}}"
    ]
}
###

@genreId = {{createGenre.response.body.data.id}}

### Find One Genre
GET http://localhost:3000/genres/{{genreId}}



### Create Cast Member
# @name createCastMember
POST http://localhost:3000/cast-members
Content-Type: application/json

{
    "name": "Cast Member 1",
    "type": 1
}
###

@castMemberId = {{createCastMember.response.body.data.id}}

### Find One Cast Member
GET http://localhost:3000/cast-members/{{castMemberId}}



### Create Video
# @name createVideo
POST http://localhost:3000/videos
Content-Type: application/json

{
    "title": "Video 1",
    "description": "Description 1",
    "yearLaunched": 2020,
    "isOpened": false,
    "rating": "L",
    "duration": 90,
    "categoryIds": [
        "{{categoryId}}"
    ],
    "genreIds": [
        "{{genreId}}"
    ],
    "castMemberIds": [
        "{{castMemberId}}"
    ]
}
###

@videoId = {{createVideo.response.body.data.id}}

### Find One Video
GET http://localhost:3000/videos/{{videoId}}

### Update Video
# @name updateVideo
PATCH http://localhost:3000/videos/{{videoId}}
Content-Type: application/json

{
    "title": "Video 1aaaa",
    "description": "Description 1aaaa",
    "yearLaunched": 2021,
    "isOpened": true,
    "rating": "L",
    "duration": 90,
    "categoryIds": [
        "{{categoryId}}"
    ],
    "genreIds": [
        "{{genreId}}"
    ],
    "castMemberIds": [
        "{{castMemberId}}"
    ]
}
###

### Invalid update Video request
PATCH http://localhost:3000/videos/{{videoId}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary1234

------WebKitFormBoundary1234
Content-Disposition: form-data; name="video"; filename="video.mp4"
Content-Type: video/mp4

< ./package.json
------WebKitFormBoundary1234
Content-Disposition: form-data; name="title"
Content-Type: text/plain

video teste
------WebKitFormBoundary1234--

### Upload Video file
PATCH http://localhost:3000/videos/{{videoId}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary1234

------WebKitFormBoundary1234
Content-Disposition: form-data; name="video"; filename="video.mp4"
Content-Type: video/mp4

< ./package.json
------WebKitFormBoundary1234--
