services:
  app:
    build: .
    command: ./.docker/start.sh
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      # The following volumes should be enabled if there's a problem with datetime convertion
      #- '/etc/timezone:/etc/timezone:ro'
      #- '/etc/localtime:/etc/localtime:ro'

  db:
    image: mysql:8.0.37-debian
    environment:
      - MYSQL_DATABASE=micro_videos
      - MYSQL_ROOT_PASSWORD=root
    tmpfs:
      - /var/lib/mysql
    security_opt:
      - seccomp:unconfined
